Feature 138 docx report export
Metatavu/rapurc-management pull request #139
Opened 2023-04-27 13:57 UTC by Daniilmass

Closes #138

2023-05-22 18:27 UTC, EVP1989 reviewed
Approved with comments and suggestions

2023-05-22 18:27 UTC, EVP1989 commented on src/components/docx-export/docx-export-utils.tsx
> +   * @param doc document
Add other parameters to docs

2023-05-22 18:27 UTC, EVP1989 commented on src/components/docx-export/docx-export-utils.tsx
> +   * @param doc document
same here

2023-05-22 18:27 UTC, EVP1989 commented on src/components/docx-export/docx-export-utils.tsx
> +   * Generate docx file
Same here

2023-05-22 18:27 UTC, EVP1989 commented on src/components/docx-export/helpers/image-utils.tsx
> +   * @returns
Add return value

2023-05-22 18:27 UTC, EVP1989 commented on src/components/docx-export/pages/demolition-information-page.tsx
> +  surveyInfoTableRows.push(endDateRow);
I think it should work also like this.

2023-05-22 18:27 UTC, EVP1989 commented on src/components/docx-export/pages/hazardous-materials-page.tsx
> +      hazardousMaterialsTableRows.push(hazardousMaterialTableRow);
Check syntax from previous file

2023-05-22 18:27 UTC, EVP1989 commented on src/components/docx-export/pages/hazardous-materials-page.tsx
> + *
Add parameters to docs

2023-05-22 18:27 UTC, EVP1989 commented on src/components/docx-export/pages/owner-and-building-info-page.tsx
> +  buildingInfoTableRows.push(buildingIDRow);
Check syntax

2023-05-22 18:27 UTC, EVP1989 commented on src/components/docx-export/pages/reusable-materials-page.tsx
> +  // Here we push our table to the page children
Do we need this commented code?

2023-05-22 18:27 UTC, EVP1989 commented on src/components/docx-export/pages/waste-materials-page.tsx
> +      wasteMaterialsTableRows.push(wasteMaterialTableRow);
Check syntax

2023-05-23 05:01 UTC, lauriLukkarinen requested changes

2023-05-23 05:01 UTC, lauriLukkarinen commented on src/localization/en.json
> +      "buildingInfo": "Purettavan rakennuksen tiedot:"
```suggestion
      "ownerContactPerson": "Owner's contact person:",
      "ownerAndAddress": "Building owner and address:",
      "buildingInfo": "Building info:"
```

2023-05-23 07:31 UTC, Kaemppi commented on src/components/docx-export/docx-export-utils.tsx
> +    const csvURL = window.URL.createObjectURL(docBlob);
I dont know. Was done by Daniil.

2023-05-23 07:40 UTC, Kaemppi commented on src/components/docx-export/pages/owner-and-building-info-page.tsx
> +  buildingInfoTableRows.push(buildingIDRow);
How?

2023-05-23 07:41 UTC, Kaemppi commented on src/components/docx-export/pages/waste-materials-page.tsx
> +      wasteMaterialsTableRows.push(wasteMaterialTableRow);
How should it be?

2023-05-23 07:55 UTC, Kaemppi commented on src/components/docx-export/pages/reusable-materials-page.tsx
> +  // Here we push our table to the page children
ah this below.. no I dont think so

2023-05-23 09:47 UTC, merged