Feature 50 summary page
Metatavu/rapurc-management pull request #63
Opened 2021-12-09 15:37 UTC by Chi-Chu319

resolves #50

2021-12-13 15:02 UTC, lauriLukkarinen requested changes

2021-12-13 15:02 UTC, lauriLukkarinen commented on src/components/survey/summary.tsx
> +          }
Extract inline function to its own method

2021-12-13 15:02 UTC, lauriLukkarinen commented on src/components/survey/summary.tsx
> +          { wastes.map(waste => {
extract

2021-12-13 15:02 UTC, lauriLukkarinen commented on src/components/survey/summary.tsx
> +          { hazardousWastes.map(hazardousWaste => {
extract

2021-12-13 15:02 UTC, lauriLukkarinen commented on src/localization/en.json
> +    "tons": "tonnia"
```suggestion
    "tons": "tons"
```

2021-12-13 15:02 UTC, lauriLukkarinen commented on src/localization/fi.json
>      "title": "Error",
```suggestion
    "title": "Virhe",
```

2021-12-14 09:47 UTC, Chi-Chu319 reviewed
comment

2021-12-14 13:04 UTC, lauriLukkarinen approved these changes

2021-12-14 13:39 UTC, merged